id: PB11B22F6
initial_creation_type: input
source_metadata:
  title: 'Vasubandhu: Triṃśikāvijñapti'
  language: bo
  volumes:
    f4aadc8c35f9445db60b6cdca6a6f358:
      title: CI_Verses 1-10
      base_file: CI_Verses 1-10.txt
      work_id: WDBB4B94B
    45f48a0cb2674421b9e5043984a3fff6:
      title: CI_Verses 11-20
      base_file: CI_Verses 11-20.txt
      work_id: WDC3E4D61
    49873d69f115446a887c61437dd4c893:
      title: CI_Verses 21-31
      base_file: CI_Verses 21-31.txt
      work_id: W994969E7
  chapter_to_tile:
    CI: Title
created_at: '2022-03-01T23:28:26.524552'
last_modified_at: '2022-03-01T23:28:26.524564'
